<?php
 /*
 * Project:		EQdkp-Plus
 * License:		Creative Commons - Attribution-Noncommercial-Share Alike 3.0 Unported
 * Link:		http://creativecommons.org/licenses/by-nc-sa/3.0/
 * -----------------------------------------------------------------------
 * Began:		2007
 * Date:		$Date$
 * -----------------------------------------------------------------------
 * @author		$Author$
 * @copyright	2006-2011 EQdkp-Plus Developer Team
 * @link		http://eqdkp-plus.com
 * @package		eqdkp-plus
 * @version		$Rev$
 * 
 * $Id$
 */

if ( !defined('EQDKP_INC') ){
	header('HTTP/1.0 404 Not Found');exit;
}

$realmnames = array(
	"Aegwynn",
	"Alexstrasza",
	"Alleria",
	"Aman'Thul",
	"Ambossar",
	"Anetheron",
	"Antonidas",
	"Anub'arak",
	"Area 52",
	"Arthas",
	"Arygos",
	"Azshara",
	"Baelgun",
	"Blackhand",
	"Blackmoore",
	"Blackrock",
	"Blutkessel", 
	"Dalvengyr", 
	"Das Konsortium", 
	"Das Syndikat", 
	"Der abyssische Rat",
	"Der Mithrilorden",
	"Der Rat von Dalaran", 
	"Destromath",
	"Dethecus",
	"Die Aldor",
	"Die Arguswacht",
	"Die ewige Wacht",
	"Die Nachtwache", 
	"Die Silberne Hand", 
	"Die Todeskrallen",
	"Dun Morogh", 
	"Durotan", 
	"Echsenkessel", 
	"Eredar", 
	"Festung der Stürme", 
	"Forscherliga", 
	"Frostmourne", 
	"Frostwolf",
	"Garrosh", 
	"Gilneas", 
	"Gorgonnash", 
	"Gul'dan", 
	"Kargath", 
	"Kel'Thuzad", 
	"Khaz'goroth", 
	"Kil'Jaeden", 
	"Krag'jin", 
	"Kult der Verdammten", 
	"Lordaeron", 
	"Lothar", 
	"Madmortem", 
	"Mal'Ganis", 
	"Malfurion", 
	"Malorne",
	"Malygos", 
	"Mannoroth",
	"Mug'thol", 
	"Nathrezim", 
	"Nazjatar", 
	"Nefarian", 
	"Nera'thor", 
	"Nethersturm",
	"Norgannon", 
	"Nozdormu", 
	"Onyxia", 
	"Perenolde", 
	"Proudmoore", 
	"Rajaxx",
	"Rexxar", 
	"Sen'jin", 
	"Shattrath", 
	"Taerar", 
	"Teldrassil", 
	"Terrordar", 
	"Theradras", 
	"Thrall", 
	"Tichondrius", 
	"Tirion", 
	"Todeswache", 
	"Un'Goro", 
	"Vek'lor",
	"Wrathbringer", 
	"Ysera", 
	"Zirkel des Cenarius",
	"Zuluhed", 
	
	// English Realms    
	"Aerie Peak", 
	"Agamaggan", 
	"Aggramar",
	"Ahn'Qiraj",
	"Al'Akir",
	"Alonsus", 
	"Anachronos", 
	"Arathor",
	"Argent Dawn",
	"Aszune", 
	"Auchindoun", 
	"Azjol-Nerub", 
	"Azuremyst",
	"Balnazzar", 
	"Blade's Edge",
	"Bladefist", 
	"Bloodfeather", 
	"Bloodhoof", 
	"Bloodscalp", 
	"Boulderfist", 
	"Bronze Dragonflight", 
	"Bronzebeard", 
	"Burning Blade",
	"Burning Legion",
	"Burning Steppes", 
	"Chamber of Aspects", 
	"Chromaggus", 
	"Crushridge",
	"Daggerspine", 
	"Darkmoon Faire", 
	"Darksorrow", 
	"Darkspear", 
	"Deathwing", 
	"Defias Brotherhood", 
	"Dentarg", 
	"Doomhammer",
	"Draenor",
	"Dragonblight", 
	"Dragonmaw", 
	"Drak'thul",
	"Dunemaul", 
	"Earthen Ring", 
	"Emerald Dream",
	"Emeriss", 
	"Eonar", 
	"Executus", 
	"Frostmane",
	"Frostwhisper", 
	"Genjuros", 
	"Ghostlands",
	"Grim Batol",
	"Hakkar", 
	"Haomarush", 
	"Hellfire", 
	"Hellscream",
	"Jaedenar", 
	"Karazhan", 
	"Kazzak",
	"Khadgar", 
	"Kilrogg", 
	"Kor'gall", 
	"Kul Tiras", 
	"Laughing Skull", 
	"Lightbringer", 
	"Lightning's Blade", 
	"Magtheridon", 
	"Mazrigos", 
	"Moonglade", 
	"Nagrand", 
	"Neptulon",
	"Nordrassil",
	"Outland",
	"Quel'Thalas", 
	"Ragnaros", 
	"Ravencrest",
	"Ravenholdt", 
	"Runetotem", 
	"Scarshield Legion", 
	"Shadowsong", 
	"Shattered Halls", 
	"Shattered Hand", 
	"Silvermoon", 
	"Skullcrusher",
	"Spinebreaker", 
	"Sporeggar",
	"Steamwheedle Cartel",
	"Stormrage", 
	"Stormreaver",
	"Stormscale",
	"Sunstrider", 
	"Sylvanas",
	"Talnivarr",
	"Tarren Mill",
	"Terenas", 
	"Terokkar",
	"The Maelstrom", 
	"The Sha'tar", 
	"The Venture Co.", 
	"Thunderhorn",
	"Trollbane", 
	"Turalyon", 
	"Twilight's Hammer",
	"Twisting Nether", 
	"Vashj", 
	"Vek'nilash", 
	"Wildhammer", 
	"Xavius",
	"Zenedar", 
	
	// French Realms    
	"Arak-arahm", 
	"Arathi", 
	"Archimonde",
	"Chants éternels", 
	"Cho'gall", 
	"Confrérie du Thorium", 
	"Conseil des Ombres",
	"Culte de la Rive noire", 
	"Dalaran",
	"Drek'Thar",
	"Eitrigg", 
	"Eldre'Thalas", 
	"Elune", 
	"Garona", 
	"Hyjal", 
	"Illidan",
	"Kael'thas", 
	"Khaz Modan", 
	"Kirin Tor",
	"Krasus", 
	"La Croisade écarlate", 
	"Les Clairvoyants", 
	"Les Sentinelles", 
	"Marécage de Zangar", 
	"Medivh", 
	"Naxxramas",
	"Ner'zhul", 
	"Rashgarroth", 
	"Sargeras", 
	"Sinstralis",
	"Suramar", 
	"Temple noir", 
	"Throk'Feroth", 
	"Uldaman", 
	"Varimathras", 
	"Vol'jin", 
	"Ysondre",
	
	// Spanish Realms    
	"C'Thun",
	"Dun Modr", 
	"Exodar", 
	"Los Errantes", 
	"Minahonda",
	"Sanguino",
	"Shen'dralar",
	"Tyrande",
	"Uldum",
	
	// US...
	"Aerie Peak",
	"Agamaggan",
	"Aggramar",
	"Akama",
	"Alexstrasza",
	"Alleria",
	"Altar of Storms",
	"Alterac Mountains",
	"Aman'Thul",
	"Andorhal",
	"Anetheron",
	"Antonidas",
	"Anub'arak",
	"Anvilmar",
	"Arathor",
	"Archimonde",
	"Area 52",
	"Argent Dawn",
	"Arthas",
	"Arygos",
	"Auchindoun",
	"Azgalor",
	"Azjol-Nerub",
	"Azshara",
	"Azuremyst",
	"Baelgun",
	"Balnazzar",
	"Barthilas",
	"Black Dragonflight",
	"Blackhand",
	"Blackrock",
	"Blackwater Raiders",
	"Blackwing Lair",
	"Blade's Edge",
	"Bladefist",
	"Bleeding Hollow",
	"Blood Furnace",
	"Bloodhoof",
	"Bloodscalp",
	"Bonechewer",
	"Boulderfist",
	"Bronzebeard",
	"Burning Blade",
	"Burning Legion",
	"Caelestrasz",
	"Cairne",
	"Cenarion Circle",
	"Cenarius",
	"Cho'gall",
	"Chromaggus",
	"Coilfang",
	"Crushridge",
	"Daggerspine",
	"Dalaran",
	"Dalvengyr",
	"Dark Iron",
	"Darkspear",
	"Darrowmere",
	"Dath'Remar",
	"Dawnbringer",
	"Deathwing",
	"Demon Soul",
	"Dentarg",
	"Destromath",
	"Dethecus",
	"Detheroc",
	"Doomhammer",
	"Draenor",
	"Dragonblight",
	"Dragonmaw",
	"Drak'Tharon",
	"Drak'thul",
	"Draka",
	"Drakkari",
	"Dreadmaul",
	"Drenden",
	"Dunemaul",
	"Durotan",
	"Duskwood",
	"Earthen Ring",
	"Echo Isles",
	"Eitrigg",
	"Eldre'Thalas",
	"Elune",
	"Emerald Dream",
	"Eonar",
	"Eredar",
	"Executus",
	"Exodar",
	"Farstriders",
	"Feathermoon",
	"Fenris",
	"Firetree",
	"Fizzcrank",
	"Frostmane",
	"Frostmourne",
	"Frostwolf",
	"Galakrond",
	"Garithos",
	"Garona",
	"Ghostlands",
	"Gilneas",
	"Gnomeregan",
	"Gorefiend",
	"Gorgonnash",
	"Greymane",
	"Grizzly Hills",
	"Gul'dan",
	"Gundrak",
	"Gurubashi",
	"Hakkar",
	"Haomarush",
	"Hellscream",
	"Hydraxis",
	"Hyjal",
	"Icecrown",
	"Illidan",
	"Jaedenar",
	"Jubei'Thos",
	"Kael'thas",
	"Kalecgos",
	"Kargath",
	"Kel'Thuzad",
	"Khadgar",
	"Khaz Modan",
	"Khaz'goroth",
	"Kil'Jaeden",
	"Kilrogg",
	"Kirin Tor",
	"Korgath",
	"Korialstrasz",
	"Kul Tiras",
	"Laughing Skull",
	"Lethon",
	"Lightbringer",
	"Lightning's Blade",
	"Lightninghoof",
	"Llane",
	"Lothar",
	"Madoran",
	"Maelstrom",
	"Magtheridon",
	"Maiev",
	"Mal'Ganis",
	"Malfurion",
	"Malorne",
	"Malygos",
	"Mannoroth",
	"Medivh",
	"Misha",
	"Mok'Nathal",
	"Moon Guard",
	"Moonrunner",
	"Mug'thol",
	"Muradin",
	"Nagrand",
	"Nathrezim",
	"Nazgrel",
	"Nazjatar",
	"Ner'zhul",
	"Nordrassil",
	"Norgannon",
	"Onyxia",
	"Perenolde",
	"Proudmoore",
	"Quel'dorei",
	"Quel'Thalas",
	"Ragnaros",
	"Ravencrest",
	"Ravenholdt",
	"Rexxar",
	"Rivendare",
	"Runetotem",
	"Sargeras",
	"Saurfang",
	"Scarlet Crusade",
	"Scilla",
	"Sen'Jin",
	"Sentinels",
	"Shadow Council",
	"Shadowmoon",
	"Shadowsong",
	"Shandris",
	"Shattered Halls",
	"Shattered Hand",
	"Shu'halo",
	"Silver Hand",
	"Silvermoon",
	"Sisters of Elune",
	"Skullcrusher",
	"Skywall",
	"Smolderthorn",
	"Spinebreaker",
	"Spirestone",
	"Staghelm",
	"Steamwheedle Cartel",
	"Stonemaul",
	"Stormrage",
	"Stormreaver",
	"Stormscale",
	"Suramar",
	"Tanaris",
	"Terenas",
	"Terokkar",
	"Thaurissan",
	"The Forgotten Coast",
	"The Scryers",
	"The Underbog",
	"The Venture Co",
	"Thorium Brotherhood",
	"Thrall",
	"Thunderhorn",
	"Thunderlord",
	"Tichondrius",
	"Tortheldrin",
	"Trollbane",
	"Turalyon",
	"Twisting Nether",
	"Uldaman",
	"Uldum",
	"Undermine",
	"Ursin",
	"Uther",
	"Vashj",
	"Vek'nilash",
	"Velen",
	"Warsong",
	"Whisperwind",
	"WildHammer",
	"Windrunner",
	"Ysera",
	"Ysondre",
	"Zangarmarsh",
	"Zul'jin",
	"Zuluhed",
);

$realmnames = array_unique($realmnames);

$settingsdata_admin = array(
	'game' => array(
		'wowsettings' => array(
			'uc_faction'	=> array(
				'name'		=> 'uc_faction',
				'fieldtype'	=> 'dropdown',
				'size'		=> '1',
				'options'	=> registry::register('game')->get('factions'),
				'default'	=> 'alliance'
			),
			'uc_server_loc'	=> array(
				'name'		=> 'uc_server_loc',
				'fieldtype' => 'dropdown',
				'size'		=> '1',
				'options'	=> array('eu' => 'EU', 'us' => 'US', 'tw' => 'TW', 'kr' => 'KR', 'cn' => 'CN'),
			),
			'uc_data_lang'	=> array(
				'name'		=> 'uc_data_lang',
				'fieldtype' => 'dropdown',
				'size'		=> '1',
				'options'	=> array(
								'en_US' => 'English',
								'es_MX' => 'Mexican',
								'pt_BR' => 'Brasil',
								'en_GB' => 'English (GB)',
								'es_ES' => 'Spanish',
								'fr_FR' => 'French',
								'ru_RU' => 'Russian',
								'de_DE'	=> 'German',
								'pt_PT'	=> 'Portuguese',
								'ko_KR'	=> 'Korean',
								'zh_TW'	=> 'Taiwanese',
								'zh_CN'	=> 'Chinese'
							),
			),
			'uc_servername'	=> array(
				'name'		=> 'uc_servername',
				'fieldtype'	=> 'autocomplete',
				'size'		=> '21',
				'edecode'	=> true,
				'options'	=> $realmnames,
			),
			'uc_lockserver'	=> array(
				'name'		=> 'uc_lockserver',
				'fieldtype'	=> 'checkbox',
				'size'		=> false,
				'options'	=> false,
			)
		)
	)
);

?>