

AutoInviteCompleteList = {
		[1] = {
			["name"] = "Dmxman",
			["inGroup"] = false,
			["status"] = "unknown",
			["group"] = "-",
			["level"] = 60,
			["comment"] = "W\195\188rfelergebnis: |CFFB700B770 |CFFFF50FF ",
			["eClass"] = "WARRIOR",
		},
		[2] = {
			["name"] = "Dorash",
			["inGroup"] = false,
			["status"] = "unknown",
			["group"] = "-",
			["level"] = 60,
			["comment"] = "W\195\188rfelergebnis: |CFFB700B772 |CFFFF50FF ",
			["eClass"] = "DRUID",
		},
		[3] = {
			["name"] = "Tazer",
			["inGroup"] = false,
			["status"] = "unknown",
			["group"] = "-",
			["level"] = 60,
			["comment"] = "W\195\188rfelergebnis: |CFFB700B717 |CFFFF50FF ",
			["eClass"] = "WARRIOR",
		},
		[4] = {
			["name"] = "Thalya",
			["inGroup"] = false,
			["status"] = "unknown",
			["group"] = "-",
			["level"] = 60,
			["comment"] = "W\195\188rfelergebnis: |CFFB700B776 |CFFFF50FF ",
			["eClass"] = "PRIEST",
		},
		[5] = {
			["name"] = "Kiesouw",
			["inGroup"] = false,
			["status"] = "unknown",
			["group"] = "-",
			["level"] = 60,
			["comment"] = "W\195\188rfelergebnis: |CFFB700B797 |CFFFF50FF ",
			["eClass"] = "PALADIN",
		},
		[6] = {
			["name"] = "Anat",
			["inGroup"] = false,
			["status"] = "unknown",
			["group"] = "-",
			["level"] = 60,
			["comment"] = "W\195\188rfelergebnis: |CFFB700B798 |CFFFF50FF ",
			["eClass"] = "DRUID",
		},
		[7] = {
			["name"] = "Fandarie",
			["inGroup"] = false,
			["status"] = "unknown",
			["group"] = "-",
			["level"] = 60,
			["comment"] = "W\195\188rfelergebnis: |CFFB700B713 |CFFFF50FF ",
			["eClass"] = "DRUID",
		},
		[8] = {
			["name"] = "Urox",
			["inGroup"] = false,
			["status"] = "unknown",
			["group"] = "-",
			["level"] = 60,
			["comment"] = "W\195\188rfelergebnis: |CFFB700B773 |CFFFF50FF ",
			["eClass"] = "WARLOCK",
		},
		[9] = {
			["name"] = "Kriegstoff",
			["inGroup"] = false,
			["status"] = "unknown",
			["group"] = "-",
			["level"] = 58,
			["comment"] = "W\195\188rfelergebnis: |CFFB700B792 |CFFFF50FF ",
			["eClass"] = "PALADIN",
		},
		[10] = {
			["name"] = "Todeselfe",
			["inGroup"] = false,
			["status"] = "unknown",
			["group"] = "-",
			["level"] = 60,
			["comment"] = "W\195\188rfelergebnis: |CFFB700B785 |CFFFF50FF ",
			["eClass"] = "HUNTER",
		},
		[11] = {
			["name"] = "Zuxxor",
			["inGroup"] = false,
			["status"] = "unknown",
			["group"] = "-",
			["level"] = 60,
			["comment"] = "W\195\188rfelergebnis: |CFFB700B770 |CFFFF50FF ",
			["eClass"] = "PALADIN",
		},
		[12] = {
			["name"] = "Serodin",
			["inGroup"] = false,
			["status"] = "unknown",
			["group"] = "-",
			["level"] = 60,
			["comment"] = "W\195\188rfelergebnis: |CFFB700B791 |CFFFF50FF Kann mich auch verspäten ",
			["eClass"] = "HUNTER",
		},
		[13] = {
			["name"] = "Soror",
			["inGroup"] = false,
			["status"] = "unknown",
			["group"] = "-",
			["level"] = 60,
			["comment"] = "W\195\188rfelergebnis: |CFFB700B780 |CFFFF50FF ",
			["eClass"] = "WARRIOR",
		},
		[14] = {
			["name"] = "Monky",
			["inGroup"] = false,
			["status"] = "unknown",
			["group"] = "-",
			["level"] = 60,
			["comment"] = "W\195\188rfelergebnis: |CFFB700B769 |CFFFF50FF werd sehn wie ich zeit hab, muss für ne nachprüfung lernen.",
			["eClass"] = "WARRIOR",
		},
		[15] = {
			["name"] = "Feantur",
			["inGroup"] = false,
			["status"] = "unknown",
			["group"] = "-",
			["level"] = 60,
			["comment"] = "W\195\188rfelergebnis: |CFFB700B783 |CFFFF50FF ",
			["eClass"] = "MAGE",
		},
		[16] = {
			["name"] = "Otard",
			["inGroup"] = false,
			["status"] = "unknown",
			["group"] = "-",
			["level"] = 60,
			["comment"] = "W\195\188rfelergebnis: |CFFB700B778 |CFFFF50FF ",
			["eClass"] = "HUNTER",
		},
		[17] = {
			["name"] = "Viraelf",
			["inGroup"] = false,
			["status"] = "unknown",
			["group"] = "-",
			["level"] = 60,
			["comment"] = "W\195\188rfelergebnis: |CFFB700B766 |CFFFF50FF ",
			["eClass"] = "MAGE",
		},
		[18] = {
			["name"] = "Killas",
			["inGroup"] = false,
			["status"] = "unknown",
			["group"] = "-",
			["level"] = 60,
			["comment"] = "W\195\188rfelergebnis: |CFFB700B78 |CFFFF50FF ",
			["eClass"] = "PALADIN",
		},
		[19] = {
			["name"] = "Rayken",
			["inGroup"] = false,
			["status"] = "unknown",
			["group"] = "-",
			["level"] = 60,
			["comment"] = "W\195\188rfelergebnis: |CFFB700B782 |CFFFF50FF ",
			["eClass"] = "DRUID",
		},
		[20] = {
			["name"] = "Darwerin",
			["inGroup"] = false,
			["status"] = "unknown",
			["group"] = "-",
			["level"] = 60,
			["comment"] = "W\195\188rfelergebnis: |CFFB700B739 |CFFFF50FF ",
			["eClass"] = "ROGUE",
		},
		[21] = {
			["name"] = "Lasthero",
			["inGroup"] = false,
			["status"] = "unknown",
			["group"] = "-",
			["level"] = 60,
			["comment"] = "W\195\188rfelergebnis: |CFFB700B72 |CFFFF50FF ",
			["eClass"] = "WARLOCK",
		},
		[22] = {
			["name"] = "Theox",
			["inGroup"] = false,
			["status"] = "unknown",
			["group"] = "-",
			["level"] = 60,
			["comment"] = "W\195\188rfelergebnis: |CFFB700B77 |CFFFF50FF huhu",
			["eClass"] = "PALADIN",
		},
		[23] = {
			["name"] = "Lain",
			["inGroup"] = false,
			["status"] = "unknown",
			["group"] = "-",
			["level"] = 60,
			["comment"] = "W\195\188rfelergebnis: |CFFB700B750 |CFFFF50FF Zu 80% bin ich da",
			["eClass"] = "HUNTER",
		},
		[24] = {
			["name"] = "Mindon",
			["inGroup"] = false,
			["status"] = "unknown",
			["group"] = "-",
			["level"] = 60,
			["comment"] = "W\195\188rfelergebnis: |CFFB700B791 |CFFFF50FF ",
			["eClass"] = "HUNTER",
		},
		[25] = {
			["name"] = "Navara",
			["inGroup"] = false,
			["status"] = "unknown",
			["group"] = "-",
			["level"] = 60,
			["comment"] = "W\195\188rfelergebnis: |CFFB700B773 |CFFFF50FF ",
			["eClass"] = "PRIEST",
		},
		[26] = {
			["name"] = "Gaara",
			["inGroup"] = false,
			["status"] = "unknown",
			["group"] = "-",
			["level"] = 60,
			["comment"] = "W\195\188rfelergebnis: |CFFB700B789 |CFFFF50FF ",
			["eClass"] = "ROGUE",
		},
		[27] = {
			["name"] = "Silvanas",
			["inGroup"] = false,
			["status"] = "unknown",
			["group"] = "-",
			["level"] = 60,
			["comment"] = "W\195\188rfelergebnis: |CFFB700B765 |CFFFF50FF ",
			["eClass"] = "WARRIOR",
		},
		[28] = {
			["name"] = "Shari",
			["inGroup"] = false,
			["status"] = "unknown",
			["group"] = "-",
			["level"] = 60,
			["comment"] = "W\195\188rfelergebnis: |CFFB700B776 |CFFFF50FF ",
			["eClass"] = "ROGUE",
		},
		[29] = {
			["name"] = "Vermithrax",
			["inGroup"] = false,
			["status"] = "unknown",
			["group"] = "-",
			["level"] = 60,
			["comment"] = "W\195\188rfelergebnis: |CFFB700B731 |CFFFF50FF ",
			["eClass"] = "WARRIOR",
		},
		[30] = {
			["name"] = "Deedlet",
			["inGroup"] = false,
			["status"] = "unknown",
			["group"] = "-",
			["level"] = 60,
			["comment"] = "W\195\188rfelergebnis: |CFFB700B763 |CFFFF50FF ",
			["eClass"] = "DRUID",
		},
		[31] = {
			["name"] = "Sorthasil",
			["inGroup"] = false,
			["status"] = "unknown",
			["group"] = "-",
			["level"] = 60,
			["comment"] = "W\195\188rfelergebnis: |CFFB700B714 |CFFFF50FF wenn was dazwischen kommt.. sry ^^",
			["eClass"] = "WARLOCK",
		},
		[32] = {
			["name"] = "Basstuner",
			["inGroup"] = false,
			["status"] = "unknown",
			["group"] = "-",
			["level"] = 0,
			["comment"] = "W\195\188rfelergebnis: |CFFB700B725 |CFFFF50FF weis aber nich wie kange ich kann",
			["eClass"] = "MAGE",
		},
		[33] = {
			["name"] = "Avalus",
			["inGroup"] = false,
			["status"] = "unknown",
			["group"] = "-",
			["level"] = 60,
			["comment"] = "W\195\188rfelergebnis: |CFFB700B775 |CFFFF50FF ",
			["eClass"] = "MAGE",
		},
		[34] = {
			["name"] = "Julee",
			["inGroup"] = false,
			["status"] = "unknown",
			["group"] = "-",
			["level"] = 60,
			["comment"] = "W\195\188rfelergebnis: |CFFB700B728 |CFFFF50FF ich hoffe es klappt zeitlich",
			["eClass"] = "ROGUE",
		},
		[35] = {
			["name"] = "Lille",
			["inGroup"] = false,
			["status"] = "unknown",
			["group"] = "-",
			["level"] = 60,
			["comment"] = "W\195\188rfelergebnis: |CFFB700B760 |CFFFF50FF ",
			["eClass"] = "DRUID",
		},
		[36] = {
			["name"] = "Sladana",
			["inGroup"] = false,
			["status"] = "unknown",
			["group"] = "-",
			["level"] = 60,
			["comment"] = "W\195\188rfelergebnis: |CFFB700B729 |CFFFF50FF ",
			["eClass"] = "WARRIOR",
		},
		[37] = {
			["name"] = "Thorly",
			["inGroup"] = false,
			["status"] = "unknown",
			["group"] = "-",
			["level"] = 60,
			["comment"] = "W\195\188rfelergebnis: |CFFB700B748 |CFFFF50FF ",
			["eClass"] = "PALADIN",
		},
		[38] = {
			["name"] = "Solaika",
			["inGroup"] = false,
			["status"] = "unknown",
			["group"] = "-",
			["level"] = 60,
			["comment"] = "W\195\188rfelergebnis: |CFFB700B710 |CFFFF50FF ",
			["eClass"] = "HUNTER",
		},
		[39] = {
			["name"] = "Wessex",
			["inGroup"] = false,
			["status"] = "unknown",
			["group"] = "-",
			["level"] = 60,
			["comment"] = "W\195\188rfelergebnis: |CFFB700B770 |CFFFF50FF muss schauen wir lange ich morgen weg bin aber versuche auf jedenfall zu kommen",
			["eClass"] = "MAGE",
		},}
AutoInviteConfig = {
	["ifWisper"] = 1,
	["modActive"] = 0,
	}
AutoInviteSavedList = {}