
### Style presets
INSERT INTO eqdkp_styles (style_id, style_name, template_path, body_background, body_link, body_link_style, body_hlink, body_hlink_style, header_link, header_link_style, header_hlink, header_hlink_style, tr_color1, tr_color2, th_color1, fontface1, fontface2, fontface3, fontsize1, fontsize2, fontsize3, fontcolor1, fontcolor2, fontcolor3, fontcolor_neg, fontcolor_pos, table_border_width, table_border_color, table_border_style, input_color, input_border_width, input_border_color, input_border_style) VALUES (1, 'Default', 'default', '212042', '31308C', 'underline', '000084', 'underline', 'CECFEF', 'underline', 'E6E6F5', 'underline', 'EFEFEF', 'FFFFFF', '424563', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 10, 11, 12, '000000', 'CECFEF', '000000', 'F80000', '008800', 1, '7B819A', 'solid', 'FFFFFF', 1, '000000', 'solid');
INSERT INTO eqdkp_styles (style_id, style_name, template_path, body_background, body_link, body_link_style, body_hlink, body_hlink_style, header_link, header_link_style, header_hlink, header_hlink_style, tr_color1, tr_color2, th_color1, fontface1, fontface2, fontface3, fontsize1, fontsize2, fontsize3, fontcolor1, fontcolor2, fontcolor3, fontcolor_neg, fontcolor_pos, table_border_width, table_border_color, table_border_style, input_color, input_border_width, input_border_color, input_border_style) VALUES (2, 'Old School', 'default', 'FFFFFF', '000000', 'underline', '000000', 'underline', '000000', 'underline', '000000', 'underline', 'BCBFCB', 'D3D7DE', '7B819A', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 10, 11, 12, '000000', '000000', '000000', 'F80000', '008800', 0, '000000', 'solid', 'FFFFFF', 1, '000000', 'solid');
INSERT INTO eqdkp_styles (style_id, style_name, template_path, body_background, body_link, body_link_style, body_hlink, body_hlink_style, header_link, header_link_style, header_hlink, header_hlink_style, tr_color1, tr_color2, th_color1, fontface1, fontface2, fontface3, fontsize1, fontsize2, fontsize3, fontcolor1, fontcolor2, fontcolor3, fontcolor_neg, fontcolor_pos, table_border_width, table_border_color, table_border_style, input_color, input_border_width, input_border_color, input_border_style) VALUES (3, 'EQdkp VB', 'default', '8080A6', '000000', 'underline', 'FB4400', 'underline', 'FFF788', 'none', 'FFF788', 'underline', 'F1F1F1', 'DFDFDF', '606096', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 10, 11, 12, '000000', '000000', '000000', 'F80000', '008800', 0, '000000', 'none', 'FFFFFF', 1, '000000', 'solid');
INSERT INTO eqdkp_styles (style_id, style_name, template_path, body_background, body_link, body_link_style, body_hlink, body_hlink_style, header_link, header_link_style, header_hlink, header_hlink_style, tr_color1, tr_color2, th_color1, fontface1, fontface2, fontface3, fontsize1, fontsize2, fontsize3, fontcolor1, fontcolor2, fontcolor3, fontcolor_neg, fontcolor_pos, table_border_width, table_border_color, table_border_style, input_color, input_border_width, input_border_color, input_border_style) VALUES (4, 'Blueish', 'default', '939EAF', '586273', 'underline', 'FFF9F3', 'underline', 'FFFFFF', 'none', 'FFFFFF', 'none', 'D6DAE6', 'BFC5D3', '828FA2', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 10, 11, 12, '000000', 'FFFFFF', 'FFFFFF', 'F80000', '008800', 1, '455164', 'solid', '727E93', 1, 'FFFFFF', 'solid');
INSERT INTO eqdkp_styles (style_id, style_name, template_path, body_background, body_link, body_link_style, body_hlink, body_hlink_style, header_link, header_link_style, header_hlink, header_hlink_style, tr_color1, tr_color2, th_color1, fontface1, fontface2, fontface3, fontsize1, fontsize2, fontsize3, fontcolor1, fontcolor2, fontcolor3, fontcolor_neg, fontcolor_pos, table_border_width, table_border_color, table_border_style, input_color, input_border_width, input_border_color, input_border_style) VALUES (5, 'EQdkp Items', 'default', 'FFFFFF', '2F415D', 'underline', 'E98219', 'underline', 'FFFFFF', 'underline', 'E98219', 'underline', 'F1F1F3', 'E3E4E8', '263B58', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 10, 11, 12, '000000', '000000', '000000', 'F80000', '008800', 1, '1D2846', 'solid', 'FFFFFF', 1, '000000', 'solid');
INSERT INTO eqdkp_styles (style_id, style_name, template_path, body_background, body_link, body_link_style, body_hlink, body_hlink_style, header_link, header_link_style, header_hlink, header_hlink_style, tr_color1, tr_color2, th_color1, fontface1, fontface2, fontface3, fontsize1, fontsize2, fontsize3, fontcolor1, fontcolor2, fontcolor3, fontcolor_neg, fontcolor_pos, table_border_width, table_border_color, table_border_style, input_color, input_border_width, input_border_color, input_border_style) VALUES (6, 'aallix Silver', 'default', 'FFFFFF', '555555', 'none', 'EC8500', 'underline', '555555', 'none', 'EC8500', 'underline', 'F2F2F2', 'FAFAFA', 'E0E0E0', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 10, 11, 12, '000000', '000000', '000000', 'F80000', '008800', 1, '999999', 'solid', 'D1D1D1', 1, '000000', 'solid');
INSERT INTO eqdkp_styles (style_id, style_name, template_path, body_background, body_link, body_link_style, body_hlink, body_hlink_style, header_link, header_link_style, header_hlink, header_hlink_style, tr_color1, tr_color2, th_color1, fontface1, fontface2, fontface3, fontsize1, fontsize2, fontsize3, fontcolor1, fontcolor2, fontcolor3, fontcolor_neg, fontcolor_pos, table_border_width, table_border_color, table_border_style, input_color, input_border_width, input_border_color, input_border_style) VALUES (7, 'Penguin', 'default', 'FFFFFF', '000000', 'underline', '000000', 'underline', '000000', 'underline', '000000', 'underline', 'EEEEEE', 'FFFFFF', 'FFCC00', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 10, 11, 12, '000000', '000000', '000000', 'F80000', '008800', 1, 'FFCC00', 'solid', 'FFFFFF', 1, '000000', 'solid');
INSERT INTO eqdkp_styles (style_id, style_name, template_path, body_background, body_link, body_link_style, body_hlink, body_hlink_style, header_link, header_link_style, header_hlink, header_hlink_style, tr_color1, tr_color2, th_color1, fontface1, fontface2, fontface3, fontsize1, fontsize2, fontsize3, fontcolor1, fontcolor2, fontcolor3, fontcolor_neg, fontcolor_pos, table_border_width, table_border_color, table_border_style, input_color, input_border_width, input_border_color, input_border_style) VALUES (8, 'Collab', 'default', 'FFFFFF', '354A55', 'underline', '5B7F93', 'underline', '5B7F93', 'underline', '354A55', 'underline', 'F5F5F5', 'DEE7EB', 'C4D3DB', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 10, 11, 12, '000000', '000000', '000000', 'F80000', '008800', 1, '999999', 'solid', 'FFFFFF', 1, '000000', 'solid');
INSERT INTO eqdkp_styles (style_id, style_name, template_path, body_background, body_link, body_link_style, body_hlink, body_hlink_style, header_link, header_link_style, header_hlink, header_hlink_style, tr_color1, tr_color2, th_color1, fontface1, fontface2, fontface3, fontsize1, fontsize2, fontsize3, fontcolor1, fontcolor2, fontcolor3, fontcolor_neg, fontcolor_pos, table_border_width, table_border_color, table_border_style, input_color, input_border_width, input_border_color, input_border_style) VALUES (9, 'EQdkp Invision', 'default', 'FFFFFF', '000000', 'underline', '465584', 'underline', '3A4F6C', 'none', '3A4F6C', 'underline', 'E4EAF2', 'DFE6EF', 'BCD0ED', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 10, 11, 12, '000000', '000000', '000000', 'F80000', '008800', 1, '345487', 'solid', 'FFFFFF', 1, '000000', 'solid');
INSERT INTO eqdkp_styles (style_id, style_name, template_path, body_background, body_link, body_link_style, body_hlink, body_hlink_style, header_link, header_link_style, header_hlink, header_hlink_style, tr_color1, tr_color2, th_color1, fontface1, fontface2, fontface3, fontsize1, fontsize2, fontsize3, fontcolor1, fontcolor2, fontcolor3, fontcolor_neg, fontcolor_pos, table_border_width, table_border_color, table_border_style, input_color, input_border_width, input_border_color, input_border_style) VALUES (10, 'dkpUA', 'default', '253546', 'C6C6C6', 'underline', '576695', 'underline', 'C6C6C6', 'none', 'C6C6C6', 'underline', '39495A', '283846', '1F2F3D', 'Verdana', 'Verdana', 'Verdana', 10, 11, 12, 'C6C6C6', 'C6C6C6', '000000', 'FF0000', '00C000', 1, '60707E', 'solid', 'FFFFFF', 1, '60707E', 'solid');
INSERT INTO eqdkp_styles (style_id, style_name, template_path, body_background, body_link, body_link_style, body_hlink, body_hlink_style, header_link, header_link_style, header_hlink, header_hlink_style, tr_color1, tr_color2, th_color1, fontface1, fontface2, fontface3, fontsize1, fontsize2, fontsize3, fontcolor1, fontcolor2, fontcolor3, fontcolor_neg, fontcolor_pos, table_border_width, table_border_color, table_border_style, input_color, input_border_width, input_border_color, input_border_style) VALUES (11, 'subSilver', 'default', 'FFFFFF', '006699', 'underline', 'DD6900', 'underline', 'FFA34F', 'none', 'FFA34F', 'underline', 'DEE3E7', 'EFEFEF', '1073A5', 'Verdana, Arial', 'Verdana, Arial', 'Verdana, Arial', 10, 11, 12, '000000', '000000', '000000', 'F80000', '008800', 1, '006699', 'solid', 'FFFFFF', 1, '000000', 'solid');
INSERT INTO eqdkp_styles (style_id, style_name, template_path, body_background, body_link, body_link_style, body_hlink, body_hlink_style, header_link, header_link_style, header_hlink, header_hlink_style, tr_color1, tr_color2, th_color1, fontface1, fontface2, fontface3, fontsize1, fontsize2, fontsize3, fontcolor1, fontcolor2, fontcolor3, fontcolor_neg, fontcolor_pos, table_border_width, table_border_color, table_border_style, input_color, input_border_width, input_border_color, input_border_style) VALUES (12, 'EQdkp VB2', 'default', 'FFFFFF', '000000', 'underline', 'FF4400', 'underline', 'FFF788', 'none', 'FFF788', 'underline', 'F1F1F1', 'DFDFDF', '8080A6', 'Verdana, Arial', 'Verdana, Arial', 'Verdana, Arial', 10, 11, 12, '000000', '000000', '000000', 'F80000', '008800', 1, '555576', 'solid', 'FFFFFF', 1, '000000', 'solid');
INSERT INTO eqdkp_styles (style_id, style_name, template_path, body_background, body_link, body_link_style, body_hlink, body_hlink_style, header_link, header_link_style, header_hlink, header_hlink_style, tr_color1, tr_color2, th_color1, fontface1, fontface2, fontface3, fontsize1, fontsize2, fontsize3, fontcolor1, fontcolor2, fontcolor3, fontcolor_neg, fontcolor_pos, table_border_width, table_border_color, table_border_style, input_color, input_border_width, input_border_color, input_border_style) VALUES (13, 'EQCPS', 'default', '7B7984', '151F41', 'underline', '800000', 'underline', 'FFFFFF', 'none', 'FFFFFF', 'none', 'CECBCE', 'BDBABD', '424952', 'Verdana, Arial', 'Verdana, Arial', 'Verdana, Arial', 10, 11, 12, '000000', '000000', '000000', '800000', '008000', 1, '000000', 'solid', 'C0C0C0', 1, '000000', 'solid');

#WOW
INSERT INTO eqdkp_styles (style_id, style_name, template_path, body_background, body_link, body_link_style, body_hlink, body_hlink_style, header_link, header_link_style, header_hlink, header_hlink_style, tr_color1, tr_color2, th_color1, fontface1, fontface2, fontface3, fontsize1, fontsize2, fontsize3, fontcolor1, fontcolor2, fontcolor3, fontcolor_neg, fontcolor_pos, table_border_width, table_border_color, table_border_style, input_color, input_border_width, input_border_color, input_border_style) VALUES (14, 'wow_style', 'wow_style', '000000', '003366', 'underline', 'C60000', 'underline', '003366', 'underline', 'C60000', 'underline', 'F2F2F2', 'FAFAFA', '', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 10, 11, 12, '003366', 'CBA300', '003366', 'F80000', '008800', 1, '000000', 'solid', 'D1D1D1', 1, '000000', 'solid');
#Moon
INSERT INTO eqdkp_styles (style_id, style_name, template_path, body_background, body_link, body_link_style, body_hlink, body_hlink_style, header_link, header_link_style, header_hlink, header_hlink_style, tr_color1, tr_color2, th_color1, fontface1, fontface2, fontface3, fontsize1, fontsize2, fontsize3, fontcolor1, fontcolor2, fontcolor3, fontcolor_neg, fontcolor_pos, table_border_width, table_border_color, table_border_style, input_color, input_border_width, input_border_color, input_border_style) VALUES (15, 'WoWMoonclaw01', 'WoWMoonclaw01', '000000', 'CBA300', 'none', 'E98219', 'underline', 'FFDD33', 'none', 'E98219', 'none', '454545', '202020', '020725', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 10, 11, 12, 'FFFFFF', '007799', 'FFFFFF', 'F80000', '008800', 0, '1', 'solid', '000000', 1, '202020', 'solid');
#empire
INSERT INTO eqdkp_styles (style_id, style_name, template_path, body_background, body_link, body_link_style, body_hlink, body_hlink_style, header_link, header_link_style, header_hlink, header_hlink_style, tr_color1, tr_color2, th_color1, fontface1, fontface2, fontface3, fontsize1, fontsize2, fontsize3, fontcolor1, fontcolor2, fontcolor3, fontcolor_neg, fontcolor_pos, table_border_width, table_border_color, table_border_style, input_color, input_border_width, input_border_color, input_border_style) VALUES (16, ' WoWMaevahEmpire', 'WoWMaevahEmpire', '000000', 'CBA300', 'none', 'E98219', 'underline', 'FFDD33', 'none', 'E98219', 'none', '454545', '202020', '020725', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 10, 11, 12, 'FFFFFF', '007799', 'FFFFFF', 'F80000', '008800', 0, '1', 'solid', '000000', 1, '202020', 'solid');
#DefaultV
INSERT INTO eqdkp_styles (style_id, style_name, template_path, body_background, body_link, body_link_style, body_hlink, body_hlink_style, header_link, header_link_style, header_hlink, header_hlink_style, tr_color1, tr_color2, th_color1, fontface1, fontface2, fontface3, fontsize1, fontsize2, fontsize3, fontcolor1, fontcolor2, fontcolor3, fontcolor_neg, fontcolor_pos, table_border_width, table_border_color, table_border_style, input_color, input_border_width, input_border_color, input_border_style) VALUES (17, 'Default_Vert', 'defaultV', '212042', '31308C', 'underline', '000084', 'underline', 'CECFEF', 'underline', 'E6E6F5', 'underline', 'EFEFEF', 'FFFFFF', '424563', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 10, 11, 12, '000000', 'CECFEF', '000000', 'F80000', '008800', 1, '7B819A', 'solid', 'FFFFFF', 1, '000000', 'solid');
INSERT INTO eqdkp_styles (style_id, style_name, template_path, body_background, body_link, body_link_style, body_hlink, body_hlink_style, header_link, header_link_style, header_hlink, header_hlink_style, tr_color1, tr_color2, th_color1, fontface1, fontface2, fontface3, fontsize1, fontsize2, fontsize3, fontcolor1, fontcolor2, fontcolor3, fontcolor_neg, fontcolor_pos, table_border_width, table_border_color, table_border_style, input_color, input_border_width, input_border_color, input_border_style) VALUES (18, 'Old_School_Vert', 'defaultV', 'FFFFFF', '000000', 'underline', '000000', 'underline', '000000', 'underline', '000000', 'underline', 'BCBFCB', 'D3D7DE', '7B819A', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 10, 11, 12, '000000', '000000', '000000', 'F80000', '008800', 0, '000000', 'solid', 'FFFFFF', 1, '000000', 'solid');
INSERT INTO eqdkp_styles (style_id, style_name, template_path, body_background, body_link, body_link_style, body_hlink, body_hlink_style, header_link, header_link_style, header_hlink, header_hlink_style, tr_color1, tr_color2, th_color1, fontface1, fontface2, fontface3, fontsize1, fontsize2, fontsize3, fontcolor1, fontcolor2, fontcolor3, fontcolor_neg, fontcolor_pos, table_border_width, table_border_color, table_border_style, input_color, input_border_width, input_border_color, input_border_style) VALUES (19, 'EQdkp VB_Vert', 'defaultV', '8080A6', '000000', 'underline', 'FB4400', 'underline', 'FFF788', 'none', 'FFF788', 'underline', 'F1F1F1', 'DFDFDF', '606096', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 10, 11, 12, '000000', '000000', '000000', 'F80000', '008800', 0, '000000', 'none', 'FFFFFF', 1, '000000', 'solid');
INSERT INTO eqdkp_styles (style_id, style_name, template_path, body_background, body_link, body_link_style, body_hlink, body_hlink_style, header_link, header_link_style, header_hlink, header_hlink_style, tr_color1, tr_color2, th_color1, fontface1, fontface2, fontface3, fontsize1, fontsize2, fontsize3, fontcolor1, fontcolor2, fontcolor3, fontcolor_neg, fontcolor_pos, table_border_width, table_border_color, table_border_style, input_color, input_border_width, input_border_color, input_border_style) VALUES (20, 'Blueish_Vert', 'defaultV', '939EAF', '586273', 'underline', 'FFF9F3', 'underline', 'FFFFFF', 'none', 'FFFFFF', 'none', 'D6DAE6', 'BFC5D3', '828FA2', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 10, 11, 12, '000000', 'FFFFFF', 'FFFFFF', 'F80000', '008800', 1, '455164', 'solid', '727E93', 1, 'FFFFFF', 'solid');
INSERT INTO eqdkp_styles (style_id, style_name, template_path, body_background, body_link, body_link_style, body_hlink, body_hlink_style, header_link, header_link_style, header_hlink, header_hlink_style, tr_color1, tr_color2, th_color1, fontface1, fontface2, fontface3, fontsize1, fontsize2, fontsize3, fontcolor1, fontcolor2, fontcolor3, fontcolor_neg, fontcolor_pos, table_border_width, table_border_color, table_border_style, input_color, input_border_width, input_border_color, input_border_style) VALUES (21, 'EQdkp Items_Vert', 'defaultV', 'FFFFFF', '2F415D', 'underline', 'E98219', 'underline', 'FFFFFF', 'underline', 'E98219', 'underline', 'F1F1F3', 'E3E4E8', '263B58', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 10, 11, 12, '000000', '000000', '000000', 'F80000', '008800', 1, '1D2846', 'solid', 'FFFFFF', 1, '000000', 'solid');
INSERT INTO eqdkp_styles (style_id, style_name, template_path, body_background, body_link, body_link_style, body_hlink, body_hlink_style, header_link, header_link_style, header_hlink, header_hlink_style, tr_color1, tr_color2, th_color1, fontface1, fontface2, fontface3, fontsize1, fontsize2, fontsize3, fontcolor1, fontcolor2, fontcolor3, fontcolor_neg, fontcolor_pos, table_border_width, table_border_color, table_border_style, input_color, input_border_width, input_border_color, input_border_style) VALUES (22, 'aallix Silver_Vert', 'defaultV', 'FFFFFF', '555555', 'none', 'EC8500', 'underline', '555555', 'none', 'EC8500', 'underline', 'F2F2F2', 'FAFAFA', 'E0E0E0', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 10, 11, 12, '000000', '000000', '000000', 'F80000', '008800', 1, '999999', 'solid', 'D1D1D1', 1, '000000', 'solid');
INSERT INTO eqdkp_styles (style_id, style_name, template_path, body_background, body_link, body_link_style, body_hlink, body_hlink_style, header_link, header_link_style, header_hlink, header_hlink_style, tr_color1, tr_color2, th_color1, fontface1, fontface2, fontface3, fontsize1, fontsize2, fontsize3, fontcolor1, fontcolor2, fontcolor3, fontcolor_neg, fontcolor_pos, table_border_width, table_border_color, table_border_style, input_color, input_border_width, input_border_color, input_border_style) VALUES (23, 'Penguin_Vert', 'defaultV', 'FFFFFF', '000000', 'underline', '000000', 'underline', '000000', 'underline', '000000', 'underline', 'EEEEEE', 'FFFFFF', 'FFCC00', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 10, 11, 12, '000000', '000000', '000000', 'F80000', '008800', 1, 'FFCC00', 'solid', 'FFFFFF', 1, '000000', 'solid');
INSERT INTO eqdkp_styles (style_id, style_name, template_path, body_background, body_link, body_link_style, body_hlink, body_hlink_style, header_link, header_link_style, header_hlink, header_hlink_style, tr_color1, tr_color2, th_color1, fontface1, fontface2, fontface3, fontsize1, fontsize2, fontsize3, fontcolor1, fontcolor2, fontcolor3, fontcolor_neg, fontcolor_pos, table_border_width, table_border_color, table_border_style, input_color, input_border_width, input_border_color, input_border_style) VALUES (24, 'Collab_Vert', 'defaultV', 'FFFFFF', '354A55', 'underline', '5B7F93', 'underline', '5B7F93', 'underline', '354A55', 'underline', 'F5F5F5', 'DEE7EB', 'C4D3DB', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 10, 11, 12, '000000', '000000', '000000', 'F80000', '008800', 1, '999999', 'solid', 'FFFFFF', 1, '000000', 'solid');
INSERT INTO eqdkp_styles (style_id, style_name, template_path, body_background, body_link, body_link_style, body_hlink, body_hlink_style, header_link, header_link_style, header_hlink, header_hlink_style, tr_color1, tr_color2, th_color1, fontface1, fontface2, fontface3, fontsize1, fontsize2, fontsize3, fontcolor1, fontcolor2, fontcolor3, fontcolor_neg, fontcolor_pos, table_border_width, table_border_color, table_border_style, input_color, input_border_width, input_border_color, input_border_style) VALUES (25, 'EQdkp Invision_Vert', 'defaultV', 'FFFFFF', '000000', 'underline', '465584', 'underline', '3A4F6C', 'none', '3A4F6C', 'underline', 'E4EAF2', 'DFE6EF', 'BCD0ED', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 10, 11, 12, '000000', '000000', '000000', 'F80000', '008800', 1, '345487', 'solid', 'FFFFFF', 1, '000000', 'solid');
INSERT INTO eqdkp_styles (style_id, style_name, template_path, body_background, body_link, body_link_style, body_hlink, body_hlink_style, header_link, header_link_style, header_hlink, header_hlink_style, tr_color1, tr_color2, th_color1, fontface1, fontface2, fontface3, fontsize1, fontsize2, fontsize3, fontcolor1, fontcolor2, fontcolor3, fontcolor_neg, fontcolor_pos, table_border_width, table_border_color, table_border_style, input_color, input_border_width, input_border_color, input_border_style) VALUES (26, 'dkpUA_Vert', 'defaultV', '253546', 'C6C6C6', 'underline', '576695', 'underline', 'C6C6C6', 'none', 'C6C6C6', 'underline', '39495A', '283846', '1F2F3D', 'Verdana', 'Verdana', 'Verdana', 10, 11, 12, 'C6C6C6', 'C6C6C6', '000000', 'FF0000', '00C000', 1, '60707E', 'solid', 'FFFFFF', 1, '60707E', 'solid');
INSERT INTO eqdkp_styles (style_id, style_name, template_path, body_background, body_link, body_link_style, body_hlink, body_hlink_style, header_link, header_link_style, header_hlink, header_hlink_style, tr_color1, tr_color2, th_color1, fontface1, fontface2, fontface3, fontsize1, fontsize2, fontsize3, fontcolor1, fontcolor2, fontcolor3, fontcolor_neg, fontcolor_pos, table_border_width, table_border_color, table_border_style, input_color, input_border_width, input_border_color, input_border_style) VALUES (27, 'subSilver_Vert', 'defaultV', 'FFFFFF', '006699', 'underline', 'DD6900', 'underline', 'FFA34F', 'none', 'FFA34F', 'underline', 'DEE3E7', 'EFEFEF', '1073A5', 'Verdana, Arial', 'Verdana, Arial', 'Verdana, Arial', 10, 11, 12, '000000', '000000', '000000', 'F80000', '008800', 1, '006699', 'solid', 'FFFFFF', 1, '000000', 'solid');
INSERT INTO eqdkp_styles (style_id, style_name, template_path, body_background, body_link, body_link_style, body_hlink, body_hlink_style, header_link, header_link_style, header_hlink, header_hlink_style, tr_color1, tr_color2, th_color1, fontface1, fontface2, fontface3, fontsize1, fontsize2, fontsize3, fontcolor1, fontcolor2, fontcolor3, fontcolor_neg, fontcolor_pos, table_border_width, table_border_color, table_border_style, input_color, input_border_width, input_border_color, input_border_style) VALUES (28, 'EQdkp VB2_Vert', 'defaultV', 'FFFFFF', '000000', 'underline', 'FF4400', 'underline', 'FFF788', 'none', 'FFF788', 'underline', 'F1F1F1', 'DFDFDF', '8080A6', 'Verdana, Arial', 'Verdana, Arial', 'Verdana, Arial', 10, 11, 12, '000000', '000000', '000000', 'F80000', '008800', 1, '555576', 'solid', 'FFFFFF', 1, '000000', 'solid');
INSERT INTO eqdkp_styles (style_id, style_name, template_path, body_background, body_link, body_link_style, body_hlink, body_hlink_style, header_link, header_link_style, header_hlink, header_hlink_style, tr_color1, tr_color2, th_color1, fontface1, fontface2, fontface3, fontsize1, fontsize2, fontsize3, fontcolor1, fontcolor2, fontcolor3, fontcolor_neg, fontcolor_pos, table_border_width, table_border_color, table_border_style, input_color, input_border_width, input_border_color, input_border_style) VALUES (29, 'EQCPS_Vert', 'defaultV', '7B7984', '151F41', 'underline', '800000', 'underline', 'FFFFFF', 'none', 'FFFFFF', 'none', 'CECBCE', 'BDBABD', '424952', 'Verdana, Arial', 'Verdana, Arial', 'Verdana, Arial', 10, 11, 12, '000000', '000000', '000000', '800000', '008000', 1, '000000', 'solid', 'C0C0C0', 1, '000000', 'solid');
#WOW V new by Urox
INSERT INTO eqdkp_styles (style_id, style_name, template_path, body_background, body_link, body_link_style, body_hlink, body_hlink_style, header_link, header_link_style, header_hlink, header_hlink_style, tr_color1, tr_color2, th_color1, fontface1, fontface2, fontface3, fontsize1, fontsize2, fontsize3, fontcolor1, fontcolor2, fontcolor3, fontcolor_neg, fontcolor_pos, table_border_width, table_border_color, table_border_style, input_color, input_border_width, input_border_color, input_border_style) VALUES (30, 'wow_style_Vert', 'wow_styleV', '000000', '003366', 'underline', 'C60000', 'underline', '003366', 'underline', 'C60000', 'underline', 'F2F2F2', 'FAFAFA', '', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 10, 11, 12, '003366', 'CBA300', '003366', 'F80000', '008800', 1, '000000', 'solid', 'D1D1D1', 1, '000000', 'solid');
#MoonV
INSERT INTO eqdkp_styles (style_id, style_name, template_path, body_background, body_link, body_link_style, body_hlink, body_hlink_style, header_link, header_link_style, header_hlink, header_hlink_style, tr_color1, tr_color2, th_color1, fontface1, fontface2, fontface3, fontsize1, fontsize2, fontsize3, fontcolor1, fontcolor2, fontcolor3, fontcolor_neg, fontcolor_pos, table_border_width, table_border_color, table_border_style, input_color, input_border_width, input_border_color, input_border_style) VALUES (31, 'WoWMoonclaw01_Vert', 'WoWMoonclaw01V', '000000', 'CBA300', 'none', 'E98219', 'underline', 'FFDD33', 'none', 'E98219', 'none', '454545', '202020', '020725', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 10, 11, 12, 'FFFFFF', '007799', 'FFFFFF', 'F80000', '008800', 0, '1', 'solid', '000000', 1, '202020', 'solid');
#empireV
INSERT INTO eqdkp_styles (style_id, style_name, template_path, body_background, body_link, body_link_style, body_hlink, body_hlink_style, header_link, header_link_style, header_hlink, header_hlink_style, tr_color1, tr_color2, th_color1, fontface1, fontface2, fontface3, fontsize1, fontsize2, fontsize3, fontcolor1, fontcolor2, fontcolor3, fontcolor_neg, fontcolor_pos, table_border_width, table_border_color, table_border_style, input_color, input_border_width, input_border_color, input_border_style) VALUES (32, 'WoWMaevahEmpire_Vert', 'WoWMaevahEmpireV', '000000', 'CBA300', 'none', 'E98219', 'underline', 'FFDD33', 'none', 'E98219', 'none', '454545', '202020', '020725', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 10, 11, 12, 'FFFFFF', '007799', 'FFFFFF', 'F80000', '008800', 0, '1', 'solid', '000000', 1, '202020', 'solid');
#
#WoWV by Urox
INSERT INTO eqdkp_styles (style_id, style_name, template_path, body_background, body_link, body_link_style, body_hlink, body_hlink_style, header_link, header_link_style, header_hlink, header_hlink_style, tr_color1, tr_color2, th_color1, fontface1, fontface2, fontface3, fontsize1, fontsize2, fontsize3, fontcolor1, fontcolor2, fontcolor3, fontcolor_neg, fontcolor_pos, table_border_width, table_border_color, table_border_style, input_color, input_border_width, input_border_color, input_border_style) VALUES (33, 'wow_Vert', 'wowV', '000000', 'CBA300', 'none', 'CBA300', 'none', 'D7CEA4', 'none', 'C60000', 'none', '2F2F2F', '202020', '2D2D2D', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 'Verdana, Tahoma, Arial', 10, 11, 12, 'D7CEA4', 'CBA300', '000000', 'F80000', '008800', 1, '000000', 'solid', 'D1D1D1', 1, '000000', 'solid');

#wow3
INSERT INTO eqdkp_styles (style_id, style_name, template_path, body_background, body_link, body_link_style, body_hlink, body_hlink_style, header_link, header_link_style, header_hlink, header_hlink_style, tr_color1, tr_color2, th_color1, fontface1, fontface2, fontface3, fontsize1, fontsize2, fontsize3, fontcolor1, fontcolor2, fontcolor3, fontcolor_neg, fontcolor_pos, table_border_width, table_border_color, table_border_style, input_color, input_border_width, input_border_color, input_border_style) VALUES (34, 'wow3theme', 'wow3theme', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

  

### Style configurations
INSERT INTO eqdkp_style_config (style_id, attendees_columns, logo_path) VALUES (1, '6',  'logo_eqdkp_plus.gif');
INSERT INTO eqdkp_style_config (style_id, attendees_columns, logo_path) VALUES (2, '4',  'logo_eqdkp_plus.gif');
INSERT INTO eqdkp_style_config (style_id, attendees_columns, logo_path) VALUES (3, '6',  'logo_eqdkp_plus.gif');
INSERT INTO eqdkp_style_config (style_id, attendees_columns, logo_path) VALUES (4, '6',  'logo_eqdkp_plus.gif');
INSERT INTO eqdkp_style_config (style_id, attendees_columns, logo_path) VALUES (5, '6',  'logo_eqdkp_plus.gif');
INSERT INTO eqdkp_style_config (style_id, attendees_columns, logo_path) VALUES (6, '6',  'logo_eqdkp_plus.gif');
INSERT INTO eqdkp_style_config (style_id, attendees_columns, logo_path) VALUES (7, '6',  'logo_eqdkp_plus.gif');
INSERT INTO eqdkp_style_config (style_id, attendees_columns, logo_path) VALUES (8, '6',  'logo_eqdkp_plus.gif');
INSERT INTO eqdkp_style_config (style_id, attendees_columns, logo_path) VALUES (9, '6',  'logo_eqdkp_plus.gif');
INSERT INTO eqdkp_style_config (style_id, attendees_columns, logo_path) VALUES (10, '8', 'logo_eqdkp_plus.gif');
INSERT INTO eqdkp_style_config (style_id, attendees_columns, logo_path) VALUES (11, '8', 'logo_eqdkp_plus.gif');
INSERT INTO eqdkp_style_config (style_id, attendees_columns, logo_path) VALUES (12, '8', 'logo_eqdkp_plus.gif');
INSERT INTO eqdkp_style_config (style_id, attendees_columns, logo_path) VALUES (13, '8', 'logo_eqdkp_plus.gif');
INSERT INTO eqdkp_style_config (style_id, attendees_columns, logo_path) VALUES (14, '6', '/logo/logo_wow.gif');
INSERT INTO eqdkp_style_config (style_id, attendees_columns, logo_path) VALUES (15, '8', 'logo_wow.gif');
INSERT INTO eqdkp_style_config (style_id, attendees_columns, logo_path) VALUES (16, '6', 'logo_wow.gif');
INSERT INTO eqdkp_style_config (style_id, attendees_columns, logo_path) VALUES (17, '6', 'logo_eqdkp_plus.gif');
INSERT INTO eqdkp_style_config (style_id, attendees_columns, logo_path) VALUES (18, '4', 'logo_eqdkp_plus.gif');
INSERT INTO eqdkp_style_config (style_id, attendees_columns, logo_path) VALUES (19, '6', 'logo_eqdkp_plus.gif');
INSERT INTO eqdkp_style_config (style_id, attendees_columns, logo_path) VALUES (20, '6', 'logo_eqdkp_plus.gif');
INSERT INTO eqdkp_style_config (style_id, attendees_columns, logo_path) VALUES (21, '6', 'logo_eqdkp_plus.gif');
INSERT INTO eqdkp_style_config (style_id, attendees_columns, logo_path) VALUES (22, '6', 'logo_eqdkp_plus.gif');
INSERT INTO eqdkp_style_config (style_id, attendees_columns, logo_path) VALUES (23, '6', 'logo_eqdkp_plus.gif');
INSERT INTO eqdkp_style_config (style_id, attendees_columns, logo_path) VALUES (24, '6', 'logo_eqdkp_plus.gif');
INSERT INTO eqdkp_style_config (style_id, attendees_columns, logo_path) VALUES (25, '6', 'logo_eqdkp_plus.gif');
INSERT INTO eqdkp_style_config (style_id, attendees_columns, logo_path) VALUES (26, '8', 'logo_eqdkp_plus.gif');
INSERT INTO eqdkp_style_config (style_id, attendees_columns, logo_path) VALUES (27, '8', 'logo_eqdkp_plus.gif');
INSERT INTO eqdkp_style_config (style_id, attendees_columns, logo_path) VALUES (28, '8', 'logo_eqdkp_plus.gif');
INSERT INTO eqdkp_style_config (style_id, attendees_columns, logo_path) VALUES (29, '8', 'logo_eqdkp_plus.gif');
INSERT INTO eqdkp_style_config (style_id, attendees_columns, logo_path) VALUES (30, '6', '/logo/logo_wow.gif');
INSERT INTO eqdkp_style_config (style_id, attendees_columns, logo_path) VALUES (31, '8', 'logo_eqdkp_wow.gif');
INSERT INTO eqdkp_style_config (style_id, attendees_columns, logo_path) VALUES (32, '6', 'logo_eqdkp_wow.gif');
INSERT INTO eqdkp_style_config (style_id, attendees_columns, logo_path) VALUES (33, '6', '/logo/logo_wow.gif');
INSERT INTO eqdkp_style_config (style_id, attendees_columns, logo_path) VALUES (34, '8', '/images/wowlogo3.gif');
   
