<?php

$disclaimer ='&lt;h2&gt;Imprint&lt;/h2&gt;
&lt;p&gt;Name Prename&lt;br /&gt; Street&lt;br /&gt;ZIP Town&lt;/p&gt;
&lt;h3&gt;Contact:&lt;/h3&gt;
&lt;p&gt;Telephone:&lt;br /&gt; Email:&lt;/p&gt;
&lt;h2&gt;Disclaimer&lt;/h2&gt;
&lt;p&gt;&lt;strong&gt;Limitation of liability for internal content&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;The content of our website has been compiled with meticulous care and to the best of our knowledge. However, we cannot assume any liability for the up-to-dateness, completeness or accuracy of any of the pages.&lt;/p&gt;
&lt;p&gt;Pursuant to section 7, para. 1 of the TMG (Telemediengesetz – Tele Media Act by German law), we as service providers are liable for our own content on these pages in accordance with general laws. However, pursuant to sections 8 to 10 of the TMG, we as service providers are not under obligation to monitor external information provided or stored on our website. Once we have become aware of a specific infringement of the law, we will immediately remove the content in question. Any liability concerning this matter can only be assumed from the point in time at which the infringement becomes known to us.&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;Limitation of liability for external links&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;Our website contains links to the websites of third parties (“external links”). As the content of these websites is not under our control, we cannot assume any liability for such external content. In all cases, the provider of information of the linked websites is liable for the content and accuracy of the information provided. At the point in time when the links were placed, no infringements of the law were recognisable to us. As soon as an infringement of the law becomes known to us, we will immediately remove the link in question.&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;Copyright&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;The content and works published on this website are governed by the copyright laws of Germany. Any duplication, processing, distribution or any form of utilisation beyond the scope of copyright law shall require the prior written consent of the author or authors in question.&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;Data protection&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;A visit to our website can result in the storage on our server of information about the access (date, time, page accessed). This does not represent any analysis of personal data (e.g., name, address or e-mail address). If personal data are collected, this only occurs – to the extent possible – with the prior consent of the user of the website. Any forwarding of the data to third parties without the express consent of the user shall not take place.&lt;/p&gt;
&lt;p&gt;We would like to expressly point out that the transmission of data via the Internet (e.g., by e-mail) can offer security vulnerabilities. It is therefore impossible to safeguard the data completely against access by third parties. We cannot assume any liability for damages arising as a result of such security vulnerabilities.&lt;/p&gt;
&lt;p&gt;The use by third parties of all published contact details for the purpose of advertising is expressly excluded. We reserve the right to take legal steps in the case of the unsolicited sending of advertising information; e.g., by means of spam mail.&lt;/p&gt;
&lt;p&gt;&lt;em&gt;Source: &lt;a href=&quot;http://www.mustervorlage.net/disclaimer-muster#Englisch&quot;&gt;English Disclaimer on Mustervorlage.net&lt;/a&gt;&lt;/em&gt;&lt;/p&gt;';

$privacy ='&lt;h2&gt;Privacy Policy&lt;/h2&gt;
&lt;p&gt;We, the Operators of this Website, provide it as a public service to our users.&lt;/p&gt;
&lt;p&gt;Your privacy is important to the us. Our goal is to provide you with a personalized online experience that provides you with the information, resources, and services that are most relevant and helpful to you. This Privacy Policy has been written to describe the conditions under which this web site is being made available to you. The Privacy Policy discusses, among other things, how data obtained during your visit to this web site may be collected and used. We strongly recommend that you read the Privacy Policy carefully. By using this web site, you agree to be bound by the terms of this Privacy Policy. If you do not accept the terms of the Privacy Policy, you are directed to discontinue accessing or otherwise using the web site or any materials obtained from it. If you are dissatisfied with the web site, by all means contact us; otherwise, your only recourse is to disconnect from this site and refrain from visiting the site in the future.&lt;/p&gt;
&lt;p&gt;The process of maintaining a web site is an evolving one, and the Operators may decide at some point in the future, without advance notice, to modify the terms of this Privacy Policy. Your use of the web site, or materials obtained from the web site, indicates your assent to the Privacy Policy at the time of such use. The effective Privacy Policy will be posted on the web site, and you should check upon every visit for any changes.&lt;/p&gt;
&lt;h3&gt;Sites Covered by this Privacy Policy&lt;/h3&gt;
&lt;p&gt;This Privacy Policy applies to all the Operators-maintained web sites, domains, information portals, and registries.&lt;/p&gt;
&lt;h3&gt;Children’s Privacy&lt;/h3&gt;
&lt;p&gt;The Operators are committed to protecting the privacy needs of children, and we encourage parents and guardians to take an active role in their children’s online activities and interests. The Operators do not intentionally collect information from minors, and the Operators do not target its web site to children.&lt;/p&gt;
&lt;h3&gt;Links to Non-Operators Web Sites&lt;/h3&gt;
&lt;p&gt;The Operators’s web sites may provide links to third-party web sites for the convenience of our users. If you access those links, you will leave the Operators’s web site. the Operators do not control these third-party websites and cannot represent that their policies and practices will be consistent with this Privacy Policy. For example, other web sites may collect or use personal information about you in a manner different from that described in this document. Therefore, you should use other web sites with caution, and you do so at your own risk. We encourage you to review the privacy policy of any web site before submitting personal information.&lt;/p&gt;
&lt;h3&gt;Types of Information We Collect&lt;/h3&gt;
&lt;h4&gt;&lt;strong&gt;Non-Personal Information&lt;/strong&gt;&lt;/h4&gt;
&lt;p&gt;Non-personal information is data about usage and service operation that is not directly associated with a specific personal identity. The Operators may collect and analyze non-personal information to evaluate how visitors use the Operators’s web sites.&lt;/p&gt;
&lt;h4&gt;&lt;strong&gt;Aggregate Information&lt;/strong&gt;&lt;/h4&gt;
&lt;p&gt;The Operators may gather aggregate information, which refers to information your computer automatically provides to us and that cannot be tied back to you as a specific individual. Examples include referral data (the web sites you visited just before and just after our site), the pages viewed, time spent at our Web site, and Internet Protocol (IP) addresses. An IP address is a number that is automatically assigned to your computer whenever you access the Internet. For example, when you request a page from one of our sites, our servers log your IP address to create aggregate reports on user demographics and traffic patterns and for purposes of system administration.&lt;/p&gt;
&lt;h4&gt;&lt;strong&gt;Log Files&lt;/strong&gt;&lt;/h4&gt;
&lt;p&gt;Every time you request or download a file from the web site, the Operators may store data about these events and your IP address in a log file. The Operators may use this information to analyze trends, administer the web site, track users’ movements, and gather broad demographic information for aggregate use or for other business purposes.&lt;/p&gt;
&lt;h4&gt;&lt;a id=&quot;Cookies&quot;&gt;&lt;/a&gt;&lt;strong&gt;Cookies&lt;/strong&gt;&lt;/h4&gt;
&lt;p&gt;Our site may use a feature of your browser to set a “cookie” on your computer. Cookies are small packets of information that a web site’s computer stores on your computer. The Operators’s web sites can then read the cookies whenever you visit our site. We may use cookies in a number of ways, such as to save your password so you don’t have to re-enter it each time you visit our site, to deliver content specific to your interests and to track the pages you’ve visited. These cookies allow us to use the information we collect to customize your experience so that your visit to our site is as relevant and as valuable to you as possible.&lt;/p&gt;
&lt;p&gt;Most browser software can be set up to deal with cookies. You may modify your browser preference to provide you with choices relating to cookies. You have the choice to accept all cookies, to be notified when a cookie is set or to reject all cookies. If you choose to reject cookies, certain of the functions and conveniences of our web site may not work properly, and you may be unable to use those of the Operators’s services that require registration in order to participate, or you will have to re-register each time you visit our site. Most browsers offer instructions on how to reset the browser to reject cookies in the “Help” section of the toolbar. We do not link non-personal information from cookies to personally identifiable information without your permission.&lt;/p&gt;
&lt;h4&gt;&lt;strong&gt;Personal Information&lt;/strong&gt;&lt;/h4&gt;
&lt;p&gt;Personal information is information that is associated with your name or personal identity. The Operators use personal information to better understand your needs and interests and to provide you with better service. On some of the Operators web pages, you may be able to request information, subscribe to mailing lists, participate in online discussions, collaborate on documents, provide feedback, submit information into registries, register for events, apply for membership, or join technical committees or working groups. The types of personal information you provide to us on these pages may include name, address, phone number, e-mail address, user IDs, passwords, billing information, or credit card information.&lt;/p&gt;
&lt;h4&gt;&lt;strong&gt;Members-Only Web Sites&lt;/strong&gt;&lt;/h4&gt;
&lt;p&gt;Information you provide on Operators’s membership applications is used to create a member profile, and some information may be shared with other of the Operators’s individual member representatives and organizations. Member contact information may be provided to other members on a secure web site to encourage and facilitate collaboration, research, and the free exchange of information among the Operators’s members, but we expressly prohibit members from using member contact information to send unsolicited commercial correspondence. The Operators’s members may be automatically added to the Operators’s mailing lists. From time to time, member information may be shared with event organizers and/or other organizations that provide additional benefits to the Operators’s members. By providing us with your personal information on the membership application, you expressly consent to our storing, processing, and distributing your information for these purposes.&lt;/p&gt;
&lt;h3&gt;How We Use Your Information&lt;/h3&gt;
&lt;p&gt;The Operators may use non-personal data that is aggregated for reporting about the Operators’s web site usability, performance, and effectiveness. It may be used to improve the experience, usability, and content of the site.&lt;/p&gt;
&lt;p&gt;The Operators may use personal information to provide services that support the activities of the Operators’s members and their collaboration on the Operators’s standards and projects. When accessing the Operators’s members-only web pages, your personal user information may be tracked by the Operators in order to support collaboration, ensure authorized access, and enable communication between members.&lt;/p&gt;
&lt;p&gt;Credit card information may be collected to facilitate membership applications; or if you purchase a product or service from our website, such information will not be kept longer than necessary for providing the services requested. Credit card numbers are used only for processing payment and are not used for other purposes. Payment processing services may be provided by a third-party payment service, and a management company external to the Operators may provide support for the financial activities of the Operators. the Operators may share your personal information with its partners to facilitate these transactions.&lt;/p&gt;
&lt;h3&gt;Information Sharing&lt;/h3&gt;
&lt;p&gt;The Operators does not sell, rent, or lease any individual’s personal information or lists of email addresses to anyone for marketing purposes, and we take commercially reasonable steps to maintain the security of this information. However, the Operators reserve the right to supply any such information to any organization into which the Operators may merge in the future or to which it may make any transfer in order to enable a third party to continue part or all of its mission. We also reserve the right to release personal information to protect our systems or business, when we reasonably believe you to be in violation of our Terms of Use or if we reasonably believe you to have initiated or participated in any illegal activity. In addition, please be aware that in certain circumstances, the Operators may be obligated to release your personal information pursuant to judicial or other government subpoenas, warrants, or other orders.&lt;/p&gt;
&lt;p&gt;In keeping with our open process, the Operators may maintain publicly accessible archives for the majority of our activities. For example, posting an email to any of the Operators’s-hosted public mail lists or discussion forums, subscribing to one of our newsletters or registering for one of our public meetings may result in your email address becoming part of the publicly accessible archives.&lt;/p&gt;
&lt;p&gt;On some sites, anonymous users are allowed to post content and/or participate in forum discussions. In such a case, since no user name can be associated with such a user, the IP address number of a user is used as an identifier. When posting content or messages to a Operators site anonymously, your IP address may be revealed to the public.&lt;/p&gt;
&lt;p&gt;If you are a registered member of an Operators\'s website or email list, you should be aware that some items of your personal information may be visible to other members and to the public. The Operators’s member databases may retain information about your name, e-mail address, company affiliation (if an organizational member), and such other personal address and identifying data as you choose to supply. That data may be visible to other of the Operators’s members and to the public. Your name, e-mail address, and other information you may supply also may be associated in the Operators’s publicly accessible records with the Operators’s various committees, working groups, and similar activities that you join, in various places, including: (i) the permanently-posted attendance and membership records of those activities; (ii) documents generated by the activity, which may be permanently archived; and, (iii) along with message content, in the permanent archives of the Operators’s e-mail lists, which also may be public.&lt;/p&gt;
&lt;p&gt;Please remember that any information (including personal information) that you disclose in public areas of our web site, such as forums, message boards, and news groups, becomes public information that others may collect, circulate, and use. Because we cannot and do not control the acts of others, you should exercise caution when deciding to disclose information about yourself or others in public forums such as these.&lt;/p&gt;
&lt;p&gt;Given the international scope of the Operators websites, personal information may be visible to persons outside your country of residence, including to persons in countries that your own country’s privacy laws and regulations deem deficient in ensuring an adequate level of protection for such information. If you are unsure whether this Privacy Policy is in conflict with applicable local rules, you should not submit your information. If you are located within the European Union, you should note that your information will be transferred to the United States, which is deemed by the European Union to have inadequate data protection. Nevertheless, in accordance with local laws implementing European Union Directive 95/46/EC of 24 October 1995 (“EU Privacy Directive”) on the protection of individuals with regard to the processing of personal data and on the free movement of such data, individuals located in countries outside of the United States of America who submit personal information do thereby consent to the general use of such information as provided in this Privacy Policy and to its transfer to and/or storage in the United States of America.&lt;/p&gt;
&lt;p&gt;If you do not want your personal information collected and used by the Operators, please do not visit the Operators’s web site or apply for membership of any of the Operators\' websites or email lists.&lt;/p&gt;
&lt;h3&gt;Access to and Accuracy of Member Information&lt;/h3&gt;
&lt;p&gt;The Operators are committed to keeping the personal information of our members accurate. All the information you have submitted to us can be verified and changed. In order to do this, please email us a request. We may provide members with online access to their own personal profiles, enabling them to update or delete information at any time. To protect our members’ privacy and security, we also may take reasonable steps to verify identity, such as a user ID and password, before granting access to modify personal profile data. Certain areas of the Operators’s web sites may limit access to specific individuals through the use of passwords or other personal identifiers; a password prompt is your indication that a members-only resource is being accessed.&lt;/p&gt;
&lt;h3&gt;Security&lt;/h3&gt;
&lt;p&gt;The Operators make every effort to protect personal information by users of the web site, including using firewalls and other security measures on its servers. No server, however, is 100% secure, and you should take this into account when submitting personal or confidential information about yourself on any web site, including this one. Much of the personal information is used in conjunction with member services such as collaboration and discussion, so some types of personal information such as your name, company affiliation, and email address will be visible to other the Operators’s members and to the public. The Operators assume no liability for the interception, alteration, or misuse of the information you provide. You alone are responsible for maintaining the secrecy of your personal information. Please use care when use access this web site and provide personal information.&lt;/p&gt;
&lt;h3&gt;Opting Out&lt;/h3&gt;
&lt;p&gt;From time to time the Operators may email you electronic newsletters, announcements, surveys or other information. If you prefer not to receive any or all of these communications, you may opt out by following the directions provided within the electronic newsletters and announcements.&lt;/p&gt;
&lt;p&gt;If you have questions regarding this privacy policy, please contact us.&lt;/p&gt;
&lt;p&gt;&lt;small&gt;&lt;em&gt;Source: &lt;a href=&quot;http://forum-template.wikidot.com/legal:privacy-policy&quot; target=&quot;_blank&quot; rel=&quot;nofollow&quot;&gt;forum-template.wikidot.com&lt;/a&gt;&lt;/em&gt;&lt;/small&gt;&lt;/p&gt;
&lt;p&gt;&lt;/p&gt;
&lt;h2&gt;Privacy and the use of Facebook Social Plugins&lt;/h2&gt;
&lt;p&gt;Our website uses social plugins (“plugins”) provided by the social network facebook.com, operated by Facebook Inc., 1601 S. California Avenue, Palo Alto, CA 94304, USA (“Facebook”). The plugins are identifiable by a Facebook logo (white letter f on blue background or a thumb up icon) or the notice “Facebook Social Plugin”. For a full list of all social Plugins please see http://developers.facebook.com/plugins. When you visit a page of our website that contains a social plugin, your browser establishes a direct connection to Facebook servers. Facebook directly transfers the plugin content to your browser which embeds the latter into the website, enabling Facebook to receive information about you having accessed the respective page of our website. Thus we have no influence on the data gathered by the plugin and inform you according to our state of knowledge. The embedded plugins provide Facebook with the information that you have accessed the corresponding page of our website. If you are logged into Facebook, your visit can be assigned to your Facebook account. If you interact with the plugins, for example by clicking “Like”, or entering a comment, the corresponding information is transmitted from your browser directly to Facebook and stored by it. Even if you are not logged into Facebook, there is possibility that the plugins transmits your IP-address to Facebook. For the information on the purpose and scope of data collection and procession by Facebook, as well as your rights in this respect and settings options for protecting your privacy please visit Facebook’s privacy policy: http://www.facebook.com/policy.php. If you are a Facebook member and do not want Facebook to connect the data concerning your visit to our website with your member data already stored by Facebook, please log off Facebook before entering our website. Further you can block Facebook social plugins by using add-ons for your browser, like the “Facebook Blocker“.&lt;/p&gt;
&lt;h2&gt;&lt;strong&gt;Privacy and the use Google +1&lt;/strong&gt;&lt;/h2&gt;
&lt;p&gt;Our website uses social plugins (“plugins”) provided by the social network plus.google.com, operated by Google Inc., 1600 Amphitheatre Parkway, Mountain View, CA 94043, United States. The plugins are labeled with the Google logo, the Google +1 logo or with the addition “Google Social Plugin”. When you visit a page of our website that contains such a social plugin, your browser establishes a direct connection to Google servers. Google directly transfers the plugin content to your browser which embeds the latter into the website, enabling Google to receive information about you having accessed the respective page of our website. If you are logged into Google, your visit can be assigned to your Google account. If you interact with the plugins, for example by clicking the “+1” button, or entering a comment, the corresponding information is transmitted from your browser directly to Facebook and stored by it. For the information on the purpose and scope of data collection and procession by Google, as well as your rights in this respect and settings options for protecting your privacy please visit Google’s privacy policy: http://www.google.de/intl/en/privacy/.  If you do not want Google to connect the data concerning your visit to our website with your member data already stored by Google, please log off Google before entering our website.&lt;/p&gt;
&lt;h2&gt;&lt;strong&gt;Privacy and the use of Twitter&lt;/strong&gt;&lt;/h2&gt;
&lt;p&gt;Our website contains social plugins from twitter.com. These plugins are solely provided by Twitter Inc., 795 Folsom St., Suite 600, San Francisco, CA 94107, USA. When you visit a page of our website that contains a social plugin your browser establishes a direct connection to the servers of Twitter, which is used to retrieve the contents of the plugin. Through this process, Twitter is aware that you have visited this website. If you are logged in to Twitter while browsing this website, Twitter can match your visit with your account. By interacting with the plugin, this information is sent directly to Twitter and processed there. If you would like to opt out, please log out of Twitter before visiting this website. For the information on the purpose and scope of data collection and procession by Twitter, as well as your rights in this respect and settings options for protecting your privacy please visit Twitter’s privacy policy: http://twitter.com/privacy.&lt;/p&gt;
&lt;p&gt;&lt;/p&gt;
&lt;p&gt;&lt;em&gt;Source: &lt;a href=&quot;http://www.e-recht24.de/muster-datenschutzerklaerung.html&quot;&gt;eRecht24&lt;/a&gt;&lt;/em&gt;&lt;/p&gt;';