<?php
$lang = array(
	'itemBind'		=> array(
		1	=> 'Binds when picked up',
		2	=> 'Binds when equipped',
		3	=> 'Binds when used',
		4	=> 'Binds to Battle.net account'
	),
	'itemClass'		=> array(
		0	=> array('Consumable', 'Potion', 'Elixir', 'Flask', 'Scroll', 'Food & Drink', 'Item Enhancement', 'Bandage', 'Other'),
		1	=> array('Bag', 'Soul Bag', 'Herb Bag', 'Enchanting Bag', 'Engineering Bag', 'Gem Bag', 'Mining Bag', 'Leatherworking Bag', 'Inscription Bag', 'Tackle Box'),
		2	=> array('Axe', 'Axe', 'Bow', 'Gun', 'Mace', 'Mace', 'Polearm', 'Sword', 'Sword', 10 => 'Staff', 13 => 'Fist Weapon', 14 => 'Miscellaneous', 15 => 'Dagger', 16 => 'Thrown', 18 => 'Crossbow', 19 => 'Wand', 20 => 'Fishing Pole'),
		3	=> array('Red Gem', 'Blue Gem', 'Yellow Gem', 'Purple Gem', 'Green Gem', 'Orange Gem', 'Meta Gem', 'Simple Gem', 'Prismatic Gem', 'Hydraulic Gem', 'Cogwheel Gem'),
		4	=> array('Miscellaneous', 'Cloth', 'Leather', 'Mail', 'Plate', '', 'Shield', 'Libram', 'Idol', 'Sigil', 'Relic'),
		7	=> array('Trade Goods', 'Parts', 'Explosives', 'Devices', 'Jewelcrafting', 'Cloth', 'Leather', 'Metal & Stone', 'Meat', 'Herb', 'Elemental', 'Other', 'Enchanting', 'Materials', 'Item Enhancement'),
		9	=> array('Book', 'Leatherworking', 'Tailoring', 'Engineering', 'Blacksmithing', 'Cooking', 'Alchemy', 'First Aid', 'Enchanting', 'Fishing', 'Jewelcrafting', 'Inscription'),
		12	=> array('Quest Item'),
		13	=> array('Key'),
		15	=> array('Junk', 'Reagent', 'Pet', 'Holiday', 'Other', 'Mount'),
		16	=> array('Glyph', 'Warrior', 'Paladin', 'Hunter', 'Rogue', 'Priest', 'Death Knight', 'Shaman', 'Mage', 'Warlock', 'Monk', 'Druid')
	),
	'inventoryType'	=> array(
		1	=> 'Head',
		2	=> 'Neck',
		3	=> 'Shoulder',
		4	=> 'Shirt',
		5	=> 'Chest',
		6	=> 'Waist',
		7	=> 'Legs',
		8	=> 'Feet',
		9	=> 'Wrist',
		10	=> 'Hands',
		11	=> 'Finger',
		12	=> 'Trinket',
		13	=> 'One-hand',
		14	=> 'Shield',
		15	=> 'Ranged',
		16	=> 'Back',
		17	=> 'Two-Hand',
		18	=> 'Bag',
		20	=> 'Chest',
		21	=> 'Main-hand',
		22	=> 'Off-hand',
		23	=> 'Held in off-hand',
		25	=> 'Ranged',
		26	=> 'Ranged'
	),
	'damage'		=> 'Damage',
	'weaponSpeed'	=> 'Speed',
	'dps'			=> 'damage per second',
	'armor'			=> 'Armor',
	'bonusStats'	=> array(
		3	=> 'Agility',
		4	=> 'Strength',
		5	=> 'Intellect',
		6 	=> 'Spirit',
		7	=> 'Stamina',
		13	=> 'dodge rating',
		14	=> 'parry rating',
		31	=> 'hit rating',
		32	=> 'critical strike rating',
		35	=> 'resilience rating',
		36	=> 'haste rating',
		37	=> 'expertise rating',
		38	=> 'attack power',
		45	=> 'spell power',
		46	=> 'health regeneration',
		47	=> 'spell penetration',
		49	=> 'mastery rating',
		57	=> "PvP-Power",
	),
	'secondary_stats' => 'Equip: Increases your %s by %d.',
	'socket'		=> array(
		'red'		=> 'Red Socket',
		'blue'		=> 'Blue Socket',
		'yellow'	=> 'Yellow Socket',
		'meta'		=> 'Meta Socket',
		'prismatic'	=> 'Prismatic Socket',
		'hydraulic' => 'Hydraulic Socket',
		'cogwheel'	=> 'Cogwheel Socket'		
	),
	'socketBonus'	=> 'Socket Bonus',
	'maxDurability' => 'Durability',
	'allowableClasses' => 'Classes',
	'requiredLevel'	=> 'Requires Level',
	'requiredSkill'	=> 'Requires',
	'itemLevel'		=> 'Item Level',
	'trigger'		=> array(
		'ON_EQUIP'	=> 'Equip:',
		'ON_USE'	=> 'Use:',
		'ON_PROC'	=> 'Chance on hit:',
		'UNKNOWN'	=> 'Unknown:'
	),
	'reforged'	=> 'Reforged'
);
?>